# Generated by Django 5.0.2 on 2024-02-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='product',
            table='tbl_product',
        ),
    ]
