# Generated by Django 5.0.2 on 2024-02-21 14:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_post_member_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
