# Generated by Django 5.0.2 on 2024-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_alter_reply_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reply',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='member',
        ),
    ]
